export const COLLECTION_FETCH_COLLECTION_PENDING =
  'COLLECTION_FETCH_COLLECTION_PENDING';
export const COLLECTION_FETCH_COLLECTION_SUCCESS =
  'COLLECTION_FETCH_COLLECTION_SUCCESS';
export const COLLECTION_FETCH_COLLECTION_ERROR =
  'COLLECTION_FETCH_COLLECTION_ERROR';
  export const SHOW_MODAL = 'SHOW_MODAL';
