export const COLLECTION_FETCH_SINGLE_COLLECTION_PENDING =
  'COLLECTION_FETCH_SINGLE_COLLECTION_PENDING';
export const COLLECTION_FETCH_SINGLE_COLLECTION_SUCCESS =
  'COLLECTION_FETCH_SINGLE_COLLECTION_SUCCESS';
export const COLLECTION_FETCH_SINGLE_COLLECTION_ERROR =
  'COLLECTION_FETCH_SINGLE_COLLECTION_ERROR';
export const COLLECTION_FETCH_PHOTO_COLLECTION_PENDING =
  'COLLECTION_FETCH_PHOTO_COLLECTION_PENDING';
export const COLLECTION_FETCH_PHOTO_COLLECTION_SUCCESS =
  'COLLECTION_FETCH_PHOTO_COLLECTION_SUCCESS';
export const COLLECTION_FETCH_PHOTO_COLLECTION_ERROR =
  'COLLECTION_FETCH_PHOTO_COLLECTION_ERROR';
export const COLLECTIONS_FETCH_PHOTO_COLLECTIONS_PENDING =
  'COLLECTIONS_FETCH_PHOTO_COLLECTIONS_PENDING';
  export const COLLECTIONS_FETCH_PHOTO_COLLECTIONS_SUCCESS =
    'COLLECTIONS_FETCH_PHOTO_COLLECTIONS_SUCCESS';
  export const COLLECTIONS_FETCH_PHOTO_COLLECTIONS_ERROR =
    'COLLECTIONS_FETCH_PHOTO_COLLECTIONS_ERROR';
export const SHOW_MODAL = 'SHOW_MODAL';
