version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:22

jobs:
  lint:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run lint
          command: yarn lint

  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test --coverage
      - run:
          name: Upload coverage to Coveralls
          command: |
            ./node_modules/.bin/coveralls < coverage/lcov.info

workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test
