export const FAVORITES_ADD_PHOTO_TO_FAVORITES_SUCCESS =
  'FAVORITES_ADD_PHOTO_TO_FAVORITES_SUCCESS';
export const FAVORITES_ADD_PHOTO_TO_FAVORITES_PENDING =
  'FAVORITES_ADD_PHOTO_TO_FAVORITES_PENDING';
export const FAVORITES_ADD_PHOTO_TO_FAVORITES_ERROR =
  'FAVORITES_ADD_PHOTO_TO_FAVORITES_ERROR';
export const FAVORITES_FETCH_FAVORITES_PHOTOS_SUCCESS =
  'FAVORITES_FETCH_FAVORITES_PHOTOS_SUCCESS';
export const FAVORITES_FETCH_FAVORITES_PHOTOS_PENDING =
  'FAVORITES_FETCH_FAVORITES_PHOTOS_PENDING';
export const FAVORITES_FETCH_FAVORITES_PHOTOS_ERROR =
  'FAVORITES_FETCH_FAVORITES_PHOTOS_ERROR';
export const FAVORITES_DELETE_PHOTO_FROM_FAVORITES =
  'FAVORITES_DELETE_PHOTO_FROM_FAVORITES';
export const FAVORITES_DELETE_PHOTO_FROM_FAVORITES_ERROR =
  'FAVORITES_DELETE_PHOTO_FROM_FAVORITES_ERROR';
export const SHOW_MODAL = 'SHOW_MODAL';
