export const PHOTOS_FETCH_PHOTOS_PENDING = 'PHOTOS_FETCH_PHOTOS_PENDING';
export const PHOTOS_FETCH_PHOTOS_SUCCESS = 'PHOTOS_FETCH_PHOTOS_SUCCESS';
export const PHOTOS_FETCH_PHOTOS_ERROR = 'PHOTOS_FETCH_PHOTOS_ERROR';
export const SHOW_MODAL = 'SHOW_MODAL';
