export const USER_FETCH_USER_PENDING = 'USER_FETCH_USER_PENDING';
export const USER_FETCH_USER_SUCCESS = 'USER_FETCH_USER_SUCCESS';
export const USER_FETCH_USER_ERROR = 'USER_FETCH_USER_ERORR';
export const USER_FETCH_USER_PHOTOS_ERROR = 'USER_FETCH_USER_PHOTOS_ERROR';
export const USER_FETCH_USER_PHOTOS_PENDING = 'USER_FETCH_USER_PHOTOS_PENDING';
export const USER_FETCH_USER_PHOTOS_SUCCESS = 'USER_FETCH_USER_PHOTOS_SUCCESS';
export const USER_FETCH_USER_COLLECTIONS_SUCCESS =
  'USER_FETCH_USER_COLLECTIONS_SUCCESS';
export const USER_FETCH_USER_COLLECTIONS_PENDING =
  'USER_FETCH_USER_COLLECTIONS_PENDING';
export const USER_FETCH_USER_COLLECTIONS_ERROR =
  'USER_FETCH_USER_COLLECTIONS_PENDING';
export const USER_CLEAR_USER_PHOTOS = 'USER_CLEAR_USER_PHOTOS';
export const OPEN_MODAL = 'OPEN_MODAL';
