export const COLLECTION_FETCH_SINGLE_COLLECTION_PENDING =
  'COLLECTION_FETCH_SINGLE_COLLECTION_PENDING';
export const COLLECTION_FETCH_SINGLE_COLLECTION_SUCCESS =
  'COLLECTION_FETCH_SINGLE_COLLECTION_SUCCESS';
export const COLLECTION_FETCH_SINGLE_COLLECTION_ERROR =
  'COLLECTION_FETCH_SINGLE_COLLECTION_ERROR';
