export const PHOTO_FETCH_PHOTO_PENDING = 'PHOTO_FETCH_PHOTO_PENDING';
export const PHOTO_FETCH_PHOTO_SUCCESS = 'PHOTO_FETCH_PHOTO_SUCCESS';
export const PHOTO_FETCH_PHOTO_ERROR = 'PHOTO_FETCH_PHOTO_ERROR';
export const SHOW_MODAL = 'SHOW_MODAL';
