export const USER_FETCH_USER_PHOTOS_PENDING = 'USER_FETCH_USER_PHOTOS_PENDING';
export const USER_FETCH_USER_PHOTOS_SUCCESS = 'USER_FETCH_USER_PHOTOS_SUCCESS';
export const USER_FETCH_USER_PHOTOS_ERROR = 'USER_FETCH_USER_PHOTOS_ERROR';
export const USER_SHOW_MODAL = 'USER_SHOW_MODAL';
