export const SEARCH_COLLECTIONS_SUCCESS = 'SEARCH_COLLECTIONS_SUCCESS';
export const SEARCH_COLLECTIONS_ERROR = 'SEARCH_COLLECTIONS_ERROR';
export const SEARCH_COLLECTIONS_PENDING = 'SEARCH_COLLECTIONS_PENDING';
